### ISSUE TITLE
parseclan2 check throws an error

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/parse_clan2#10]
fwiw there are 08_15 files in working folders if relevant. Here's the error:

elikab01:parse_clan2 elikab$ python parse_clan2_check.py Untitled.txt 08_15_coderLN_processed.csv 
Traceback (most recent call last):
  File "parse_clan2_check.py", line 36, in <module>
    parse_clan_count(sys.argv[1])
  File "parse_clan2_check.py", line 14, in parse_clan_count
    clan_counts.append((int(line[0]), line[1].lower()))
ValueError: invalid literal for int() with base 10: '{\rtf1\ansi\ansicpg1252\cocoartf1348\cocoasubrtf170'

**Comment by andreiamatuni** [comment]
the Untitled.txt file has some weird formatting stuff in it. The script expects the txt file to just be a simple list with:

count word1
count word2
etc....

whereas the Untitled.txt in working files looks something like this:

{\rtf1\ansi\ansicpg1252\cocoartf1348\cocoasubrtf170
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural

\f0\fs24 \cf0  40 pumpkin\
 34 water\
 29 beets\
 28 squirrel\

This could be because the .txt file was saved as as a rich text format, which adds a bunch of invisible metadata into the file. I've emailed you a fixed version of the file. Running parse_clan2_check with the fixed (plain text) version gives me this:

missing from parse_clan2 output: ['ball']

missing from clan freq (but included in csv parse): ['ball', 'ball', 'run', 'ball', 'ball', 'ball', 'ball', 'ball', 'ball', 'ball', 'ball']

# of words (clan): 618

# of words (parse_clan2): 620

looks like "ball" and "run" are a problem. I'll check to see what's going on here after class.

**Comment by ebergelson** [comment]
hi--you're right, it's just the formatting of the untitled file. i didn't
think to look at it after Shaelise made it, sorry.

We should add a wiki section on how to run this script--there's some sparse
info on github but no documentation about file formats etc in the wiki.
We'll add that to the the general to-do list.
thnx
e

_Elika Bergelson, PhD_
Research Assistant Professor, University of Rochester
Center for Language Sciences | Brain and Cognitive Science Dept. |
www.bcs.rochester.edu/people/ebergelson | www.bcs.rochester.edu/seedlings/
Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=
